### ISSUE TITLE
side by side rendering only taking up half of display

### ISSUE THREAD

**Issue by skompc** [PaysPlat/DesktopSbS#1]
when I use sbs rendering the top half of the display looks normal but the bottom half is still full size, same with other rendering mode. also v2 doesn't work for me but v1 does

**Comment by PaysPlat** [comment]
Hi, Can you send me screenshots of your case ?
Thank you

**Comment by skompc** [comment]
here u go
![my screen](https://cloud.githubusercontent.com/assets/5279725/26277998/8ab6a53c-3d57-11e7-9e45-538f70046696.png)

**Comment by PaysPlat** [comment]
For your issue, it is a Windows bug corrected by Microsoft in Windows 10 Creators Update.
This main update is progressively deployed since beginning of April. 
You can download it manually here https://www.microsoft.com/en-us/software-download/windows10
 
After update, let me know if DesktopSbS works correctly.
 
Bye
 
PaysPlat
